//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.ServiceReference, version 5.0.61118.0
// 
namespace HLP.Entries.ViewModel.pontoServicoLocal {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="pontoServicoLocal.Iwcf_Funcionario_Controle_Horas_Ponto")]
    public interface Iwcf_Funcionario_Controle_Horas_Ponto {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/Iwcf_Funcionario_Controle_Horas_Ponto/GetAllFuncionario_Contro" +
            "le_Horas_Ponto", ReplyAction="http://tempuri.org/Iwcf_Funcionario_Controle_Horas_Ponto/GetAllFuncionario_Contro" +
            "le_Horas_PontoResponse")]
        System.IAsyncResult BeginGetAllFuncionario_Controle_Horas_Ponto(int idFuncionario, System.DateTime dRelogioPonto, System.AsyncCallback callback, object asyncState);
        
        System.Collections.Generic.List<HLP.Entries.Model.RecursosHumanos.Funcionario_Controle_Horas_PontoModel> EndGetAllFuncionario_Controle_Horas_Ponto(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/Iwcf_Funcionario_Controle_Horas_Ponto/Save", ReplyAction="http://tempuri.org/Iwcf_Funcionario_Controle_Horas_Ponto/SaveResponse")]
        System.IAsyncResult BeginSave(HLP.Entries.Model.RecursosHumanos.Funcionario_Controle_Horas_PontoModel objFuncionario_Controle_Horas_Ponto, int idEmpresa, System.AsyncCallback callback, object asyncState);
        
        HLP.Entries.Model.RecursosHumanos.Funcionario_Controle_Horas_PontoModel EndSave(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/Iwcf_Funcionario_Controle_Horas_Ponto/GetFuncionario", ReplyAction="http://tempuri.org/Iwcf_Funcionario_Controle_Horas_Ponto/GetFuncionarioResponse")]
        System.IAsyncResult BeginGetFuncionario(string xCodigoAlternativo, System.AsyncCallback callback, object asyncState);
        
        HLP.Entries.Model.RecursosHumanos.FuncionarioModel EndGetFuncionario(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/Iwcf_Funcionario_Controle_Horas_Ponto/UserCanRegisterPonto", ReplyAction="http://tempuri.org/Iwcf_Funcionario_Controle_Horas_Ponto/UserCanRegisterPontoResp" +
            "onse")]
        System.IAsyncResult BeginUserCanRegisterPonto(string xCodigoAlternativo, int idEmpresa, System.AsyncCallback callback, object asyncState);
        
        string EndUserCanRegisterPonto(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Iwcf_Funcionario_Controle_Horas_PontoChannel : HLP.Entries.ViewModel.pontoServicoLocal.Iwcf_Funcionario_Controle_Horas_Ponto, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetAllFuncionario_Controle_Horas_PontoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetAllFuncionario_Controle_Horas_PontoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.Generic.List<HLP.Entries.Model.RecursosHumanos.Funcionario_Controle_Horas_PontoModel> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.Generic.List<HLP.Entries.Model.RecursosHumanos.Funcionario_Controle_Horas_PontoModel>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SaveCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public SaveCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public HLP.Entries.Model.RecursosHumanos.Funcionario_Controle_Horas_PontoModel Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((HLP.Entries.Model.RecursosHumanos.Funcionario_Controle_Horas_PontoModel)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetFuncionarioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetFuncionarioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public HLP.Entries.Model.RecursosHumanos.FuncionarioModel Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((HLP.Entries.Model.RecursosHumanos.FuncionarioModel)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UserCanRegisterPontoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public UserCanRegisterPontoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Iwcf_Funcionario_Controle_Horas_PontoClient : System.ServiceModel.ClientBase<HLP.Entries.ViewModel.pontoServicoLocal.Iwcf_Funcionario_Controle_Horas_Ponto>, HLP.Entries.ViewModel.pontoServicoLocal.Iwcf_Funcionario_Controle_Horas_Ponto {
        
        private BeginOperationDelegate onBeginGetAllFuncionario_Controle_Horas_PontoDelegate;
        
        private EndOperationDelegate onEndGetAllFuncionario_Controle_Horas_PontoDelegate;
        
        private System.Threading.SendOrPostCallback onGetAllFuncionario_Controle_Horas_PontoCompletedDelegate;
        
        private BeginOperationDelegate onBeginSaveDelegate;
        
        private EndOperationDelegate onEndSaveDelegate;
        
        private System.Threading.SendOrPostCallback onSaveCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetFuncionarioDelegate;
        
        private EndOperationDelegate onEndGetFuncionarioDelegate;
        
        private System.Threading.SendOrPostCallback onGetFuncionarioCompletedDelegate;
        
        private BeginOperationDelegate onBeginUserCanRegisterPontoDelegate;
        
        private EndOperationDelegate onEndUserCanRegisterPontoDelegate;
        
        private System.Threading.SendOrPostCallback onUserCanRegisterPontoCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public Iwcf_Funcionario_Controle_Horas_PontoClient() {
        }
        
        public Iwcf_Funcionario_Controle_Horas_PontoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Iwcf_Funcionario_Controle_Horas_PontoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Iwcf_Funcionario_Controle_Horas_PontoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Iwcf_Funcionario_Controle_Horas_PontoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<GetAllFuncionario_Controle_Horas_PontoCompletedEventArgs> GetAllFuncionario_Controle_Horas_PontoCompleted;
        
        public event System.EventHandler<SaveCompletedEventArgs> SaveCompleted;
        
        public event System.EventHandler<GetFuncionarioCompletedEventArgs> GetFuncionarioCompleted;
        
        public event System.EventHandler<UserCanRegisterPontoCompletedEventArgs> UserCanRegisterPontoCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult HLP.Entries.ViewModel.pontoServicoLocal.Iwcf_Funcionario_Controle_Horas_Ponto.BeginGetAllFuncionario_Controle_Horas_Ponto(int idFuncionario, System.DateTime dRelogioPonto, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetAllFuncionario_Controle_Horas_Ponto(idFuncionario, dRelogioPonto, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.Generic.List<HLP.Entries.Model.RecursosHumanos.Funcionario_Controle_Horas_PontoModel> HLP.Entries.ViewModel.pontoServicoLocal.Iwcf_Funcionario_Controle_Horas_Ponto.EndGetAllFuncionario_Controle_Horas_Ponto(System.IAsyncResult result) {
            return base.Channel.EndGetAllFuncionario_Controle_Horas_Ponto(result);
        }
        
        private System.IAsyncResult OnBeginGetAllFuncionario_Controle_Horas_Ponto(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int idFuncionario = ((int)(inValues[0]));
            System.DateTime dRelogioPonto = ((System.DateTime)(inValues[1]));
            return ((HLP.Entries.ViewModel.pontoServicoLocal.Iwcf_Funcionario_Controle_Horas_Ponto)(this)).BeginGetAllFuncionario_Controle_Horas_Ponto(idFuncionario, dRelogioPonto, callback, asyncState);
        }
        
        private object[] OnEndGetAllFuncionario_Controle_Horas_Ponto(System.IAsyncResult result) {
            System.Collections.Generic.List<HLP.Entries.Model.RecursosHumanos.Funcionario_Controle_Horas_PontoModel> retVal = ((HLP.Entries.ViewModel.pontoServicoLocal.Iwcf_Funcionario_Controle_Horas_Ponto)(this)).EndGetAllFuncionario_Controle_Horas_Ponto(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetAllFuncionario_Controle_Horas_PontoCompleted(object state) {
            if ((this.GetAllFuncionario_Controle_Horas_PontoCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetAllFuncionario_Controle_Horas_PontoCompleted(this, new GetAllFuncionario_Controle_Horas_PontoCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetAllFuncionario_Controle_Horas_PontoAsync(int idFuncionario, System.DateTime dRelogioPonto) {
            this.GetAllFuncionario_Controle_Horas_PontoAsync(idFuncionario, dRelogioPonto, null);
        }
        
        public void GetAllFuncionario_Controle_Horas_PontoAsync(int idFuncionario, System.DateTime dRelogioPonto, object userState) {
            if ((this.onBeginGetAllFuncionario_Controle_Horas_PontoDelegate == null)) {
                this.onBeginGetAllFuncionario_Controle_Horas_PontoDelegate = new BeginOperationDelegate(this.OnBeginGetAllFuncionario_Controle_Horas_Ponto);
            }
            if ((this.onEndGetAllFuncionario_Controle_Horas_PontoDelegate == null)) {
                this.onEndGetAllFuncionario_Controle_Horas_PontoDelegate = new EndOperationDelegate(this.OnEndGetAllFuncionario_Controle_Horas_Ponto);
            }
            if ((this.onGetAllFuncionario_Controle_Horas_PontoCompletedDelegate == null)) {
                this.onGetAllFuncionario_Controle_Horas_PontoCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetAllFuncionario_Controle_Horas_PontoCompleted);
            }
            base.InvokeAsync(this.onBeginGetAllFuncionario_Controle_Horas_PontoDelegate, new object[] {
                        idFuncionario,
                        dRelogioPonto}, this.onEndGetAllFuncionario_Controle_Horas_PontoDelegate, this.onGetAllFuncionario_Controle_Horas_PontoCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult HLP.Entries.ViewModel.pontoServicoLocal.Iwcf_Funcionario_Controle_Horas_Ponto.BeginSave(HLP.Entries.Model.RecursosHumanos.Funcionario_Controle_Horas_PontoModel objFuncionario_Controle_Horas_Ponto, int idEmpresa, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginSave(objFuncionario_Controle_Horas_Ponto, idEmpresa, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HLP.Entries.Model.RecursosHumanos.Funcionario_Controle_Horas_PontoModel HLP.Entries.ViewModel.pontoServicoLocal.Iwcf_Funcionario_Controle_Horas_Ponto.EndSave(System.IAsyncResult result) {
            return base.Channel.EndSave(result);
        }
        
        private System.IAsyncResult OnBeginSave(object[] inValues, System.AsyncCallback callback, object asyncState) {
            HLP.Entries.Model.RecursosHumanos.Funcionario_Controle_Horas_PontoModel objFuncionario_Controle_Horas_Ponto = ((HLP.Entries.Model.RecursosHumanos.Funcionario_Controle_Horas_PontoModel)(inValues[0]));
            int idEmpresa = ((int)(inValues[1]));
            return ((HLP.Entries.ViewModel.pontoServicoLocal.Iwcf_Funcionario_Controle_Horas_Ponto)(this)).BeginSave(objFuncionario_Controle_Horas_Ponto, idEmpresa, callback, asyncState);
        }
        
        private object[] OnEndSave(System.IAsyncResult result) {
            HLP.Entries.Model.RecursosHumanos.Funcionario_Controle_Horas_PontoModel retVal = ((HLP.Entries.ViewModel.pontoServicoLocal.Iwcf_Funcionario_Controle_Horas_Ponto)(this)).EndSave(result);
            return new object[] {
                    retVal};
        }
        
        private void OnSaveCompleted(object state) {
            if ((this.SaveCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.SaveCompleted(this, new SaveCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void SaveAsync(HLP.Entries.Model.RecursosHumanos.Funcionario_Controle_Horas_PontoModel objFuncionario_Controle_Horas_Ponto, int idEmpresa) {
            this.SaveAsync(objFuncionario_Controle_Horas_Ponto, idEmpresa, null);
        }
        
        public void SaveAsync(HLP.Entries.Model.RecursosHumanos.Funcionario_Controle_Horas_PontoModel objFuncionario_Controle_Horas_Ponto, int idEmpresa, object userState) {
            if ((this.onBeginSaveDelegate == null)) {
                this.onBeginSaveDelegate = new BeginOperationDelegate(this.OnBeginSave);
            }
            if ((this.onEndSaveDelegate == null)) {
                this.onEndSaveDelegate = new EndOperationDelegate(this.OnEndSave);
            }
            if ((this.onSaveCompletedDelegate == null)) {
                this.onSaveCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnSaveCompleted);
            }
            base.InvokeAsync(this.onBeginSaveDelegate, new object[] {
                        objFuncionario_Controle_Horas_Ponto,
                        idEmpresa}, this.onEndSaveDelegate, this.onSaveCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult HLP.Entries.ViewModel.pontoServicoLocal.Iwcf_Funcionario_Controle_Horas_Ponto.BeginGetFuncionario(string xCodigoAlternativo, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetFuncionario(xCodigoAlternativo, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HLP.Entries.Model.RecursosHumanos.FuncionarioModel HLP.Entries.ViewModel.pontoServicoLocal.Iwcf_Funcionario_Controle_Horas_Ponto.EndGetFuncionario(System.IAsyncResult result) {
            return base.Channel.EndGetFuncionario(result);
        }
        
        private System.IAsyncResult OnBeginGetFuncionario(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string xCodigoAlternativo = ((string)(inValues[0]));
            return ((HLP.Entries.ViewModel.pontoServicoLocal.Iwcf_Funcionario_Controle_Horas_Ponto)(this)).BeginGetFuncionario(xCodigoAlternativo, callback, asyncState);
        }
        
        private object[] OnEndGetFuncionario(System.IAsyncResult result) {
            HLP.Entries.Model.RecursosHumanos.FuncionarioModel retVal = ((HLP.Entries.ViewModel.pontoServicoLocal.Iwcf_Funcionario_Controle_Horas_Ponto)(this)).EndGetFuncionario(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetFuncionarioCompleted(object state) {
            if ((this.GetFuncionarioCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetFuncionarioCompleted(this, new GetFuncionarioCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetFuncionarioAsync(string xCodigoAlternativo) {
            this.GetFuncionarioAsync(xCodigoAlternativo, null);
        }
        
        public void GetFuncionarioAsync(string xCodigoAlternativo, object userState) {
            if ((this.onBeginGetFuncionarioDelegate == null)) {
                this.onBeginGetFuncionarioDelegate = new BeginOperationDelegate(this.OnBeginGetFuncionario);
            }
            if ((this.onEndGetFuncionarioDelegate == null)) {
                this.onEndGetFuncionarioDelegate = new EndOperationDelegate(this.OnEndGetFuncionario);
            }
            if ((this.onGetFuncionarioCompletedDelegate == null)) {
                this.onGetFuncionarioCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetFuncionarioCompleted);
            }
            base.InvokeAsync(this.onBeginGetFuncionarioDelegate, new object[] {
                        xCodigoAlternativo}, this.onEndGetFuncionarioDelegate, this.onGetFuncionarioCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult HLP.Entries.ViewModel.pontoServicoLocal.Iwcf_Funcionario_Controle_Horas_Ponto.BeginUserCanRegisterPonto(string xCodigoAlternativo, int idEmpresa, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginUserCanRegisterPonto(xCodigoAlternativo, idEmpresa, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        string HLP.Entries.ViewModel.pontoServicoLocal.Iwcf_Funcionario_Controle_Horas_Ponto.EndUserCanRegisterPonto(System.IAsyncResult result) {
            return base.Channel.EndUserCanRegisterPonto(result);
        }
        
        private System.IAsyncResult OnBeginUserCanRegisterPonto(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string xCodigoAlternativo = ((string)(inValues[0]));
            int idEmpresa = ((int)(inValues[1]));
            return ((HLP.Entries.ViewModel.pontoServicoLocal.Iwcf_Funcionario_Controle_Horas_Ponto)(this)).BeginUserCanRegisterPonto(xCodigoAlternativo, idEmpresa, callback, asyncState);
        }
        
        private object[] OnEndUserCanRegisterPonto(System.IAsyncResult result) {
            string retVal = ((HLP.Entries.ViewModel.pontoServicoLocal.Iwcf_Funcionario_Controle_Horas_Ponto)(this)).EndUserCanRegisterPonto(result);
            return new object[] {
                    retVal};
        }
        
        private void OnUserCanRegisterPontoCompleted(object state) {
            if ((this.UserCanRegisterPontoCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.UserCanRegisterPontoCompleted(this, new UserCanRegisterPontoCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void UserCanRegisterPontoAsync(string xCodigoAlternativo, int idEmpresa) {
            this.UserCanRegisterPontoAsync(xCodigoAlternativo, idEmpresa, null);
        }
        
        public void UserCanRegisterPontoAsync(string xCodigoAlternativo, int idEmpresa, object userState) {
            if ((this.onBeginUserCanRegisterPontoDelegate == null)) {
                this.onBeginUserCanRegisterPontoDelegate = new BeginOperationDelegate(this.OnBeginUserCanRegisterPonto);
            }
            if ((this.onEndUserCanRegisterPontoDelegate == null)) {
                this.onEndUserCanRegisterPontoDelegate = new EndOperationDelegate(this.OnEndUserCanRegisterPonto);
            }
            if ((this.onUserCanRegisterPontoCompletedDelegate == null)) {
                this.onUserCanRegisterPontoCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnUserCanRegisterPontoCompleted);
            }
            base.InvokeAsync(this.onBeginUserCanRegisterPontoDelegate, new object[] {
                        xCodigoAlternativo,
                        idEmpresa}, this.onEndUserCanRegisterPontoDelegate, this.onUserCanRegisterPontoCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override HLP.Entries.ViewModel.pontoServicoLocal.Iwcf_Funcionario_Controle_Horas_Ponto CreateChannel() {
            return new Iwcf_Funcionario_Controle_Horas_PontoClientChannel(this);
        }
        
        private class Iwcf_Funcionario_Controle_Horas_PontoClientChannel : ChannelBase<HLP.Entries.ViewModel.pontoServicoLocal.Iwcf_Funcionario_Controle_Horas_Ponto>, HLP.Entries.ViewModel.pontoServicoLocal.Iwcf_Funcionario_Controle_Horas_Ponto {
            
            public Iwcf_Funcionario_Controle_Horas_PontoClientChannel(System.ServiceModel.ClientBase<HLP.Entries.ViewModel.pontoServicoLocal.Iwcf_Funcionario_Controle_Horas_Ponto> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginGetAllFuncionario_Controle_Horas_Ponto(int idFuncionario, System.DateTime dRelogioPonto, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[2];
                _args[0] = idFuncionario;
                _args[1] = dRelogioPonto;
                System.IAsyncResult _result = base.BeginInvoke("GetAllFuncionario_Controle_Horas_Ponto", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.Generic.List<HLP.Entries.Model.RecursosHumanos.Funcionario_Controle_Horas_PontoModel> EndGetAllFuncionario_Controle_Horas_Ponto(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.Generic.List<HLP.Entries.Model.RecursosHumanos.Funcionario_Controle_Horas_PontoModel> _result = ((System.Collections.Generic.List<HLP.Entries.Model.RecursosHumanos.Funcionario_Controle_Horas_PontoModel>)(base.EndInvoke("GetAllFuncionario_Controle_Horas_Ponto", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginSave(HLP.Entries.Model.RecursosHumanos.Funcionario_Controle_Horas_PontoModel objFuncionario_Controle_Horas_Ponto, int idEmpresa, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[2];
                _args[0] = objFuncionario_Controle_Horas_Ponto;
                _args[1] = idEmpresa;
                System.IAsyncResult _result = base.BeginInvoke("Save", _args, callback, asyncState);
                return _result;
            }
            
            public HLP.Entries.Model.RecursosHumanos.Funcionario_Controle_Horas_PontoModel EndSave(System.IAsyncResult result) {
                object[] _args = new object[0];
                HLP.Entries.Model.RecursosHumanos.Funcionario_Controle_Horas_PontoModel _result = ((HLP.Entries.Model.RecursosHumanos.Funcionario_Controle_Horas_PontoModel)(base.EndInvoke("Save", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetFuncionario(string xCodigoAlternativo, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = xCodigoAlternativo;
                System.IAsyncResult _result = base.BeginInvoke("GetFuncionario", _args, callback, asyncState);
                return _result;
            }
            
            public HLP.Entries.Model.RecursosHumanos.FuncionarioModel EndGetFuncionario(System.IAsyncResult result) {
                object[] _args = new object[0];
                HLP.Entries.Model.RecursosHumanos.FuncionarioModel _result = ((HLP.Entries.Model.RecursosHumanos.FuncionarioModel)(base.EndInvoke("GetFuncionario", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginUserCanRegisterPonto(string xCodigoAlternativo, int idEmpresa, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[2];
                _args[0] = xCodigoAlternativo;
                _args[1] = idEmpresa;
                System.IAsyncResult _result = base.BeginInvoke("UserCanRegisterPonto", _args, callback, asyncState);
                return _result;
            }
            
            public string EndUserCanRegisterPonto(System.IAsyncResult result) {
                object[] _args = new object[0];
                string _result = ((string)(base.EndInvoke("UserCanRegisterPonto", _args, result)));
                return _result;
            }
        }
    }
}
