//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.ServiceReference, version 5.0.61118.0
// 
namespace HLP.Comum.Model.camposNotNullServices {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PesquisaPadraoModelContract", Namespace="http://schemas.datacontract.org/2004/07/HLP.Comum.Model.Components")]
    public partial class PesquisaPadraoModelContract : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int CHARACTER_MAXIMUM_LENGTHField;
        
        private string COLUMN_NAMEField;
        
        private string DATA_TYPEField;
        
        private string IS_NULLABLEField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CHARACTER_MAXIMUM_LENGTH {
            get {
                return this.CHARACTER_MAXIMUM_LENGTHField;
            }
            set {
                if ((this.CHARACTER_MAXIMUM_LENGTHField.Equals(value) != true)) {
                    this.CHARACTER_MAXIMUM_LENGTHField = value;
                    this.RaisePropertyChanged("CHARACTER_MAXIMUM_LENGTH");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string COLUMN_NAME {
            get {
                return this.COLUMN_NAMEField;
            }
            set {
                if ((object.ReferenceEquals(this.COLUMN_NAMEField, value) != true)) {
                    this.COLUMN_NAMEField = value;
                    this.RaisePropertyChanged("COLUMN_NAME");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DATA_TYPE {
            get {
                return this.DATA_TYPEField;
            }
            set {
                if ((object.ReferenceEquals(this.DATA_TYPEField, value) != true)) {
                    this.DATA_TYPEField = value;
                    this.RaisePropertyChanged("DATA_TYPE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IS_NULLABLE {
            get {
                return this.IS_NULLABLEField;
            }
            set {
                if ((object.ReferenceEquals(this.IS_NULLABLEField, value) != true)) {
                    this.IS_NULLABLEField = value;
                    this.RaisePropertyChanged("IS_NULLABLE");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="camposNotNullServices.IcamposBaseDadosService")]
    public interface IcamposBaseDadosService {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IcamposBaseDadosService/getCamposNotNull", ReplyAction="http://tempuri.org/IcamposBaseDadosService/getCamposNotNullResponse")]
        System.IAsyncResult BegingetCamposNotNull(string xTabela, System.AsyncCallback callback, object asyncState);
        
        HLP.Comum.Model.camposNotNullServices.PesquisaPadraoModelContract[] EndgetCamposNotNull(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IcamposBaseDadosServiceChannel : HLP.Comum.Model.camposNotNullServices.IcamposBaseDadosService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class getCamposNotNullCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public getCamposNotNullCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public HLP.Comum.Model.camposNotNullServices.PesquisaPadraoModelContract[] Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((HLP.Comum.Model.camposNotNullServices.PesquisaPadraoModelContract[])(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class IcamposBaseDadosServiceClient : System.ServiceModel.ClientBase<HLP.Comum.Model.camposNotNullServices.IcamposBaseDadosService>, HLP.Comum.Model.camposNotNullServices.IcamposBaseDadosService {
        
        private BeginOperationDelegate onBegingetCamposNotNullDelegate;
        
        private EndOperationDelegate onEndgetCamposNotNullDelegate;
        
        private System.Threading.SendOrPostCallback ongetCamposNotNullCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public IcamposBaseDadosServiceClient() {
        }
        
        public IcamposBaseDadosServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public IcamposBaseDadosServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IcamposBaseDadosServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IcamposBaseDadosServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<getCamposNotNullCompletedEventArgs> getCamposNotNullCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult HLP.Comum.Model.camposNotNullServices.IcamposBaseDadosService.BegingetCamposNotNull(string xTabela, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BegingetCamposNotNull(xTabela, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HLP.Comum.Model.camposNotNullServices.PesquisaPadraoModelContract[] HLP.Comum.Model.camposNotNullServices.IcamposBaseDadosService.EndgetCamposNotNull(System.IAsyncResult result) {
            return base.Channel.EndgetCamposNotNull(result);
        }
        
        private System.IAsyncResult OnBegingetCamposNotNull(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string xTabela = ((string)(inValues[0]));
            return ((HLP.Comum.Model.camposNotNullServices.IcamposBaseDadosService)(this)).BegingetCamposNotNull(xTabela, callback, asyncState);
        }
        
        private object[] OnEndgetCamposNotNull(System.IAsyncResult result) {
            HLP.Comum.Model.camposNotNullServices.PesquisaPadraoModelContract[] retVal = ((HLP.Comum.Model.camposNotNullServices.IcamposBaseDadosService)(this)).EndgetCamposNotNull(result);
            return new object[] {
                    retVal};
        }
        
        private void OngetCamposNotNullCompleted(object state) {
            if ((this.getCamposNotNullCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.getCamposNotNullCompleted(this, new getCamposNotNullCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void getCamposNotNullAsync(string xTabela) {
            this.getCamposNotNullAsync(xTabela, null);
        }
        
        public void getCamposNotNullAsync(string xTabela, object userState) {
            if ((this.onBegingetCamposNotNullDelegate == null)) {
                this.onBegingetCamposNotNullDelegate = new BeginOperationDelegate(this.OnBegingetCamposNotNull);
            }
            if ((this.onEndgetCamposNotNullDelegate == null)) {
                this.onEndgetCamposNotNullDelegate = new EndOperationDelegate(this.OnEndgetCamposNotNull);
            }
            if ((this.ongetCamposNotNullCompletedDelegate == null)) {
                this.ongetCamposNotNullCompletedDelegate = new System.Threading.SendOrPostCallback(this.OngetCamposNotNullCompleted);
            }
            base.InvokeAsync(this.onBegingetCamposNotNullDelegate, new object[] {
                        xTabela}, this.onEndgetCamposNotNullDelegate, this.ongetCamposNotNullCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override HLP.Comum.Model.camposNotNullServices.IcamposBaseDadosService CreateChannel() {
            return new IcamposBaseDadosServiceClientChannel(this);
        }
        
        private class IcamposBaseDadosServiceClientChannel : ChannelBase<HLP.Comum.Model.camposNotNullServices.IcamposBaseDadosService>, HLP.Comum.Model.camposNotNullServices.IcamposBaseDadosService {
            
            public IcamposBaseDadosServiceClientChannel(System.ServiceModel.ClientBase<HLP.Comum.Model.camposNotNullServices.IcamposBaseDadosService> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BegingetCamposNotNull(string xTabela, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = xTabela;
                System.IAsyncResult _result = base.BeginInvoke("getCamposNotNull", _args, callback, asyncState);
                return _result;
            }
            
            public HLP.Comum.Model.camposNotNullServices.PesquisaPadraoModelContract[] EndgetCamposNotNull(System.IAsyncResult result) {
                object[] _args = new object[0];
                HLP.Comum.Model.camposNotNullServices.PesquisaPadraoModelContract[] _result = ((HLP.Comum.Model.camposNotNullServices.PesquisaPadraoModelContract[])(base.EndInvoke("getCamposNotNull", _args, result)));
                return _result;
            }
        }
    }
}
